[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "geoextract-gee"
version = "0.1.0"
description = "Google Earth Engine backend for geoprepare (geoextract)"
requires-python = ">=3.9"
dependencies = [
    "geoprepare",
    "earthengine-api",
    "cdsapi"
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
include = ["geoextract_gee", "geoextract_gee.*"]
